### ISSUE TITLE
Poor formatting

### ISSUE THREAD

**Issue by FreemanMakesGames** [chaseries/hi-vue-starter#1]
# You are using spaces instead of tabs. Please fix it.

**Comment by chaseries** [comment]
https://stackoverflow.blog/2017/06/15/developers-use-spaces-make-money-use-tabs/

**Comment by FreemanMakesGames** [comment]
Take your capitalism elsewhere?

**Comment by FreemanMakesGames** [comment]
> 
> 
> https://stackoverflow.blog/2017/06/15/developers-use-spaces-make-money-use-tabs/

Take your capitalism elsewhere?
